/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C) 2021, Chao-ying Fu <cfu@wavecomp.com>
 */

#ifndef __SHOGUN_H__
#define __SHOGUN_H__

#define MHARTID_HART_SHIFT	0
#define MHARTID_HART_MASK	0xf
#define MHARTID_CORE_SHIFT	4
#define MHARTID_CORE_MASK	0xff
#define MHARTID_CLUSTER_SHIFT	16
#define MHARTID_CLUSTER_MASK	0xf

#define CM_BASE_CORE_SHIFT	8
#define CM_BASE_CLUSTER_SHIFT	19

#define KINGV_MARCHID		0x8000000000000201
#define SHOGUN_TIMER_ADDR	0x16120010
#define KINGV_TIMER_ADDR	0x16108050

#define CCA_CACHE_ENABLE	0
#define CCA_BUFFER_CACHE	1
#define CCA_CACHE_DISABLE	2
#define CCA_UNCACHE_ACC		3
#define PMA_SPECULATION		(1 << 3)

#define L1_I_CACHE      0
#define L1_D_CACHE      1
#define L3_CACHE        2
#define L2_CACHE        3

#define HIT_INVALIDATE          4
#define HIT_WRITEBACK_INV       5

#define HIT_INVALIDATE_D        ((HIT_INVALIDATE << 2) | L1_D_CACHE)
#define HIT_INVALIDATE_SD       ((HIT_INVALIDATE << 2) | L2_CACHE)
#define HIT_WRITEBACK_INV_D     ((HIT_WRITEBACK_INV << 2) | L1_D_CACHE)
#define HIT_WRITEBACK_INV_SD    ((HIT_WRITEBACK_INV << 2) | L2_CACHE)

#define L1D_LINE_SIZE_SHIFT	10
#define L1D_LINE_SIZE_MASK	0x7

#define GCR_L2_CONFIG	0x16100130
#define L2_LINE_SIZE_SHIFT	8
#define L2_LINE_SIZE_MASK	0xf

#define PMP_R			0x01
#define PMP_W			0x02
#define PMP_X			0x04
#define PMP_TOR			0x8
#define PMP_NA4			0x10
#define PMP_NAPOT		0x18

#define CM_BASE			0x16100000
#define GIC_BASE		0x16120000
#define CPC_BASE		0x16200000

/* Block offsets */
#define GCR_OFF_GLOBAL		0x0000
#define GCR_OFF_LOCAL		0x2000
#define GCR_OFF_REDIRECT	0x4000

/* CPC Block offsets */
#define CPC_OFF_GLOBAL		0x0000
#define CPC_OFF_LOCAL		0x2000
#define CPC_OFF_REDIRECT	0x4000

#define CPC_PWRUP_CTL		0x0030

#define CPC_SYS_CONFIG		0x0140

#define CPC_Cx_CMD		0x0000
#define CPC_Cx_CMD_RESET	0x4

/* GCR_CONFIG */
#define GCR_CONFIG		0x0000
#define GCR_REV			0x0030
#define GCR_CONFIG_NUMCLUSTERS_SHIFT	23
#define GCR_CONFIG_NUMCLUSTERS_MASK	0x7f
#define GCR_CONFIG_NUMIOCU_SHIFT	8
#define GCR_CONFIG_NUMIOCU_MASK		0xf
#define GCR_CONFIG_NUMCORES_SHIFT	0
#define GCR_CONFIG_NUMCORES_MASK	0xff

/* GCR_REV CM versions */
#define GCR_REV_CM3		0x0800
#define GCR_REV_CM3_5		0x0900

#define GCR_Cx_REDIRECT		0x2018
#define GCR_Cx_ID		0x2028
#define GCR_Cx_ID_CLUSTER_SHIFT	8
#define GCR_Cx_ID_CLUSTER_MASK	0xff

/* GCR_Cx_REDIRECT */
#define GCR_Cx_REDIRECT_CLUSTER_EN		(0x1 << 31)
#define GCR_Cx_REDIRECT_GIC_EN			(0x1 << 30)
#define GCR_Cx_REDIRECT_BLOCK_SHIFT		24
#define GCR_Cx_REDIRECT_BLOCK_GCR_CORE_LOCAL	0x0
#define GCR_Cx_REDIRECT_BLOCK_GCR_GLOBAL	0x1
#define GCR_Cx_REDIRECT_BLOCK_GCR_DEBUG		0x2
#define GCR_Cx_REDIRECT_BLOCK_CPC_CORE_LOCAL	0x0
#define GCR_Cx_REDIRECT_BLOCK_CPC_GLOBAL	0x1
#define GCR_Cx_REDIRECT_CLUSTER_SHIFT		16
#define GCR_Cx_REDIRECT_CORE_SHIFT		8
#define GCR_Cx_REDIRECT_VP_SHIFT		0

#define GCR_MMIO_REQ_LIMIT		0x06f8
#define GCR_MMIO0_BOTTOM		0x0700
#define  GCR_MMIO0_BOTTOM_ADDR		(0xffffffffull << 16)
#define  GCR_MMIO0_BOTTOM_PORT_SHIFT	2
#define  GCR_MMIO0_BOTTOM_PORT		(0xf << 2)
#define  GCR_MMIO0_BOTTOM_DISABLE_LIMIT	(0x1 << 1)
#define  GCR_MMIO0_BOTTOM_ENABLE	(0x1 << 0)
#define GCR_MMIO0_TOP			0x0708
#define  GCR_MMIO0_TOP_ADDR		(0xffffffffull << 16)
#define GCR_MMIO1_BOTTOM		0x0710

#define CONFIG_MIPS_CM_MMIO_LIMIT	4

#define KINGV_GCR_C0_COH_EN	0x20f8
#define KINGV_GCR_C1_COH_EN	0x21f8
#define KINGV_GCR_C2_COH_EN	0x22f8
#define KINGV_GCR_C3_COH_EN	0x23f8
#define KINGV_GCR_C4_COH_EN	0x24f8
#define KINGV_GCR_C5_COH_EN	0x25f8

#define GCR_CL_COH_EN		0x2008
#define GCR_CL_COH_EN_EN	(0x1 << 0)
#define GCR_BASE_OFFSET		0x0008
#define GIC_BASE_OFFSET		0x0080
#define CPC_BASE_OFFSET		0x0088
#define ENABLE			0x1
#define COUNT_STOP		(0x1 << 28)
#define GIC_LOCAL_SECTION_OFS	0x8000
#define GIC_VL_MASK		0x08
#define GIC_VL_RMASK		0x0c
#define GIC_VL_SMASK		0x10
#define GIC_VL_COMPARE_MAP	0x44

#define INDEXED(op, reg, idx, offset, base) \
	li	idx, offset	;\
	add	idx, idx, base	;\
	op	reg, (idx)

#define BOSTON_PLAT_BASE	0x17ffd000
#define BOSTON_PLAT_DDR3STAT	(BOSTON_PLAT_BASE + 0x14)
#define BOSTON_PLAT_DDR3STAT_CALIB	(1 << 2)
#define BOSTON_PLAT_NOCPCIE0ADDR        (BOSTON_PLAT_BASE + 0x3c)
#define BOSTON_PLAT_NOCPCIE1ADDR        (BOSTON_PLAT_BASE + 0x40)
#define BOSTON_PLAT_NOCPCIE2ADDR        (BOSTON_PLAT_BASE + 0x44)

#endif /* __SHOGUN_H__ */
